backend:
  name: github
  repo: ryandillinfelton/triangle-speech-om
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{name}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "file"}
      - {label: "Description", name: "description", widget: "markdown"}
  - name: "assorted"
    label: "Assorted"
    folder: "content/assorted"
    create: true
    slug: "{{header}}"
    fields:
      - {label: "Header", name: "header", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}
