backend:
  name: github
  repo: ryandillinfelton/triangle-speech-om
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "position", name: "position", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "file"}
      - {label: "Description", name: "body", widget: "markdown"}
  - name: "informationCards"
    label: "Information Cards"
    folder: "content/informationCards"
    create: true
    slug: "{{ header }}"
    fields:
      - {label: "Header", name: "header", widget: "string"}
      - {label: "Image", name: "image", widget: "file"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "assorted"
    label: "Assorted"
    folder: "content/assorted"
    create: true
    slug: "{{header}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Header", name: "header", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}
